# Generated by Django 3.2.7 on 2021-11-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='aRatedFilter',
            field=models.BooleanField(default=False),
        ),
    ]
