# Generated by Django 3.2.7 on 2021-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='theme',
            field=models.CharField(choices=[('1', 'default'), ('2', 'Classic theme'), ('3', 'Tv-shows theme'), ('4', 'Anime theme'), ('5', 'Tokyo Night theme'), ('6', 'Romatic Theme'), ('7', 'Bloody theme'), ('8', 'Asian theme'), ('9', 'Sad theme'), ('10', 'Lonely theme')], max_length=2),
        ),
    ]
