# Generated by Django 3.2.7 on 2021-10-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titleApp', '0002_alter_lists_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='titlemovie',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='titlemovie',
            name='imdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titlemovie',
            name='movieDB_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
