# Generated by Django 3.2.7 on 2021-10-07 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('titleApp', '0004_titlemovie_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlemovie',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='titlemovie',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lists',
            name='theme',
            field=models.CharField(choices=[('1', 'default'), ('2', 'Classic theme'), ('3', 'Tv-shows theme'), ('4', 'Anime theme'), ('5', 'Tokyo Night theme'), ('6', 'Romatic Theme'), ('7', 'Bloody theme'), ('8', 'Asian theme'), ('9', 'Sad theme'), ('10', 'Lonely theme')], default='1', max_length=2),
        ),
    ]
