# Generated by Django 3.2.7 on 2021-10-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titleApp', '0005_auto_20211007_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlemovie',
            name='title_movie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
