# Generated by Django 3.2.7 on 2021-10-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titleApp', '0006_alter_titlemovie_title_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlemovie',
            name='list_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='titleApp.lists'),
        ),
    ]
