# Generated by Django 3.2.7 on 2021-10-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titleApp', '0007_alter_titlemovie_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlemovie',
            name='media_type',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
