# Generated by Django 3.2.7 on 2021-10-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titleApp', '0008_titlemovie_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlemovie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
