# Generated by Django 3.2.7 on 2021-11-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titleApp', '0009_titlemovie_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlemovie',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
