# Generated by Django 3.2.7 on 2021-11-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titleApp', '0010_titlemovie_backdrop_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlemovie',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=850, null=True),
        ),
        migrations.AlterField(
            model_name='titlemovie',
            name='media_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='titlemovie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=850, null=True),
        ),
        migrations.AlterField(
            model_name='titlemovie',
            name='title_movie',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
